version: '3.7'
services:
  mysql-server:
    image: mysql:8.0-oracle
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./zabbix-db:/var/lib/mysql
    restart: unless-stopped
    networks:
      - zabbix-network
    deploy:
      replicas: 1
    privileged: false
  zabbix-server:
    image: zabbix/zabbix-server-mysql:7.0.15-ubuntu
    ports:
      - 10051:10051
    environment:
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: unless-stopped
    networks:
      - zabbix-network
    deploy:
      replicas: 1
    privileged: false
    depends_on:
      - mysql-server
  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-mysql:7.0.15-ubuntu
    environment:
      - ZBX_SERVER_HOST=${ZBX_SERVER_HOST}
      - DB_SERVER_HOST=${DB_SERVER_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
     - 80:8080
    restart: unless-stopped
    networks:
      - zabbix-network
    deploy:
      replicas: 1
    privileged: false
    depends_on:
      - zabbix-server
networks:
  zabbix-network:
    driver: bridge
