apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "gh-runner.labels" . | nindent 4 }}
  name: {{ include "gh-runner.fullname" . }}-deployment
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace.name }}
  {{- end }}
spec:
  replicas: {{ .Values.containers.replicas }}
  selector:
    matchLabels:
      {{- include "gh-runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "gh-runner.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ include "gh-runner.name" . }}
        image: {{ .Values.containers.image }}:{{ .Values.containers.imageTag }}
        env:
        - name: GH_RUNNER_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ include "gh-runner.fullname" . }}-token
              key: GH_RUNNER_TOKEN
        - name: GH_REPO_URL
          value: {{ .Values.containers.github_repository | lower | quote }}
        - name: GH_RUNNER_NAME
          value: ""
        - name: GH_RUNNER_GROUP
          value: {{ .Values.containers.github_runner_group | lower | quote }}
        - name: GH_RUNNER_WORK_DIR
          value: {{ .Values.containers.github_runner_workdir | lower | quote }}
        - name: GH_RUNNER_LABELS
          value: {{ .Values.containers.github_runner_labels | lower | quote }}
      resources:
        requests:
          cpu: {{ .Values.containers.resources.requests.cpu }}
          memory: {{ .Values.containers.resources.requests.memory }}
        limits:
          cpu: {{ .Values.containers.resources.limits.cpu }}
          memory: {{ .Values.containers.resources.limits.memory }}
      {{- if .Values.imagePullSecrets.enabled }}
      imagePullSecrets:
        - name: {{ include "gh-runner.fullname" . }}-image-pull-secret
      {{- end }}