{{- if .Values.imagePullSecrets.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson | quote }}
kind: Secret
metadata:
  name: {{ include "gh-runner.fullname" . }}-image-pull-secret
  {{- if .Values.namespace.create }}
  namespace: {{ .Values.namespace }}
  {{- end }}
  labels: {{- include "gh-runner.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
{{- end }}