---
- name: Fail deployment when important service is not running
  fail:
    msg: "The service {{ item }} is not running!"
  when: services[item].state != "running"

- name: Display success message
  debug:
    msg: "Service: {{ item }} is running"
...
