---
all:
  vars:
    ansible_user: "{{ lookup('env', 'T7_SSH_USER') }}"
    ansible_ssh_private_key_file: "~/.ssh/{{ ansible_user }}.key"
    ansible_port: "{{ lookup('env', 'T7_SSH_PORT') }}"
    become: true

gh_runner:
  hosts:
    docker-01.home.t7-lab.pl:
  vars:
    gh_runner_docker_dir: "/home/{{ ansible_user }}/docker/gh_runner"
    gh_runner_docker_image: "adriant7/t7-gh-runner:latest@sha256:988a7f839ce2a446100e1d901612eceb1a36b8a195b16d6b396decf95bb67f18"
    gh_runner_docker_hub_login: "{{ lookup('env', 'docker_hub_login') }}"
    gh_runner_docker_hub_password: "{{ lookup('env', 'docker_hub_password') }}"
    service_verification_services:
      - docker
      - ssh
...
