---
all:
  vars:
    ansible_user: "{{ lookup('env', 'T7_SSH_USER') }}"
    ansible_ssh_private_key_file: "~/.ssh/{{ ansible_user }}.key"
    ansible_port: "{{ lookup('env', 'T7_SSH_PORT') }}"
    become: true

gh_runner:
  hosts:
    homelab-github-runner-01.home.t7-lab.pl:
  vars:
    docker_docker_version: "20.10.24+dfsg1-1+deb12u1"
    docker_docker_compose_version: "1.29.2-3"
    gh_runner_docker_dir: "/home/{{ ansible_user }}/gh_actions"
    gh_runner_docker_image: "adriant7/gh-runner:1.0"
    service_verification_services:
      - docker
      - ssh
...
