{{- if .Values.imagePullSecrets.enabled }}
apiVersion: v1
data:
  .dockerconfigjson: {{ .Values.imagePullSecrets.dockerconfigjson | quote }}
kind: Secret
metadata:
  name: {{ .Values.imagePullSecrets.name }}
  namespace: {{ .Values.namespace }}
type: kubernetes.io/dockerconfigjson
{{- end }}