---
- name: Update Apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker.io={{ docker_docker_version }}
      - docker-compose={{ docker_docker_compose_version }}
    state: present
  notify: Restart Docker

- name: Enable Docker Engine
  ansible.builtin.service:
    name: docker
    enabled: true

- name: Add the current user to the docker group
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    groups: docker
    append: true
    state: present

- name: Log in into Docker Hub
  ansible.builtin.command:
    cmd: "docker login -u '{{ docker_hub_login }}' -p '{{ docker_hub_password }}'"
  become: false
  no_log: true

- meta: flush_handlers
...
