name: Deploy pihole

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to execute the code against
        type: choice
        options:
          - global
        required: true
        default: global
        
permissions:
  contents: read

jobs:
  ansible:
    name: Configure host
    runs-on: [self-hosted, Linux, Proxmox]
    environment: ${{ inputs.environment }}
    env: 
      T7_SSH_USER:         "${{ secrets.T7_SSH_USER }}"
      T7_SSH_PORT:         "${{ secrets.T7_SSH_PORT }}"
      T7_SSH_PORT_2:       "${{ secrets.T7_SSH_PORT_2 }}"
      ANSIBLE_ROLES_PATH:  "${{ github.workspace }}/ansible/roles/"
    defaults:
      run:
        working-directory: pihole/environments/${{ inputs.environment }}/ansible
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure SSH
        run: | 
          mkdir -p ~/.ssh 
          echo "${{ secrets.T7_SSH_KEY }}" > ~/.ssh/${{ secrets.T7_SSH_USER }}.key
          chmod 600 ~/.ssh/${{ secrets.T7_SSH_USER }}.key

      - name: Run playbook
        run: ansible-playbook -i inventory.yml prepare_pihole.yml --ssh-common-args='-o StrictHostKeyChecking=no'

      - name: Cleanup ansible key
        if: always()
        run: |
          if [[ -f ~/.ssh/${{ secrets.T7_SSH_USER }}.key ]]; then
            rm ~/.ssh/${{ secrets.T7_SSH_USER }}.key
          fi